require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'udemy_course' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RealmJS', :path => '../node_modules/realm'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

  target 'udemy_courseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'udemy_course-tvOS' do
  # Pods for udemy_course-tvOS

  target 'udemy_course-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
